default:
  image: debian:stable-20221024
stages:
  - test
  - build
  - push

unittest:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python3 python3-pip
    - pip install -r requirements.txt
    - python3 -m unittest

# build-oci:
#   stage: build
#   image: 
#     name: quay.io/buildah/stable
#   varaibles:
#     - ARTIFACT_DIR: ./artifacts
#   script:
#     - buildah bud -f Dockerfile -t stargazer:${CI_COMMIT_TAG}-latest
#     - mkdir ${ARTIFACT_DIR}
#     - buildah push stargazer:${CI_COMMIT_TAG}-latest docker-archive:${ARTIFACT_DIR}/${ARTIFACT_NAME}:${TAG}"
#   artifacts:
#     name: archive:${ARTIFACT_NAME}:${CI_JOB_ID}"
#     when: on_success
#     expire_in: 6h
#     paths:
#       - ${ARTIFACT_DIR}/"